
name: 'willows_spoon'
version: '1.0.0'
config-version: 2

profile: 'willows_spoon'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"



models:
  willows_spoon:
    sales:
      +schema: staging  
      +materialized: table
