willows_spoon:
  outputs:
    dev:
      account: ow82791.us-east-2.aws
      database: spoon_production
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}" 
      role: accountadmin
      schema: raw_source
      threads: 1
      type: snowflake
      user: vincentffaust
      warehouse: etl
  target: dev


