willows_spoon:
  target: dev 
  outputs:
    dev:
      account: me48922.us-east-2.aws
      database: spoon_dev 
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}" 
      role: accountadmin
      schema: staging 
      threads: 10
      type: snowflake
      user: vincentffaust 
      warehouse: compute_wh

    ci:
      account: me48922.us-east-2.aws
      database: spoon_ci
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}" 
      role: accountadmin
      schema: public 
      threads: 10 
      type: snowflake
      user: vincentffaust
      warehouse: compute_wh
    
    prod:
      account: me48922.us-east-2.aws
      database: spoon_prod 
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}" 
      role: accountadmin
      schema: staging 
      threads: 10 
      type: snowflake
      user: vincentffaust 
      warehouse: compute_wh


