resource_name: Shopify
definition_type: source
definition_id: 9da77001-af33-4bcd-be46-6252bf9342b9
definition_image: airbyte/source-shopify
definition_version: 0.3.4
configuration:
  shop: willows-spoon
  start_date: '2020-01-01'
  credentials:
    auth_method: api_password
    api_password: '**********'
